### PR TITLE
Fix ssh execution and improve plugin structure

### PR DESCRIPTION
**Pull request by ljader**
This PR is a follow-up to another big PR #9 - I've fixed some issues and improved plugin code.

After this PR is merged, I will release the plugin.

Fixes:
- fix incorrect merge during adding ssh-credentials support
- update to jenkinsci/jsch-plugin for loading JSch dependency
- use more modern structured form submission (simplify .jelly structure)
- remove some unused code

### CODE REVIEW

**Comment by ljader** [comment]
FYI @jenkinsci/code-reviewers

I'm planning to merge this PR myself in 2 days, since it's mostly fixes.
Honestly, the current plugin code in git repo without these fixes won't work anyway :)

**Comment by ljader** [comment]
CC also @edmund-wagner

**Comment by johnny-b-goode** [comment]
@ljader Has the migration of configurations from versions of the plugin released prior to PR #9 to this version been tested? I do not believe this was ever tested prior to PR #9 being merged. To my knowledge a release has not been created since that merge, meaning all existing configurations would go through that migration if a new release were created.

**Comment by ljader** [comment]
@johnny-b-goode I've ran few manual basic tests - I've setup new instance of Jenkins, installed 2.4 version from Jenkins Update center, created 2 ssh sites and then installed snapshot version of the plugin - it migrated the sites and credentials correctly.

However there are always some doubts, that maybe there will be setups that can have migration issues,
that's why I've turned on notification for Update Center, that this version might not be  backward compatibile.

**Comment by johnny-b-goode** [comment]
@ljader I would not worry too much about backward compatibility as much as ensuring correct migration of existing configurations.

I would also post the link to the .hpi on the Jenkins server in the PR for those who might be interested in testing, as well as in any defects the release addresses. This will provide an opportunity for the user community to do some testing prior to releasing a new version of the plugin in UC.

**Comment by ljader** [comment]
I've run into issues with migration from previous version, that's why this PR is not merged yet.
I hope to fix it by the end of March.

**Comment by ljader** [comment]
@jenknsci/code-reviewers and @edmund-wagner or @johnny-b-goode 

Could you please review this change?

**Comment by ljader** [comment]
Asking @jenkinsci/code-reviewers again for review (previous message didn't notify the group).

**Pull request merged**
