### PR TITLE
Upgrade to newest JSCH

### PR DESCRIPTION
**Pull request by InuSasha**
solved some connection issues to same ssh server configurations

### CODE REVIEW

**Comment by solomongifford** [comment]
Will resolve https://issues.jenkins-ci.org/browse/JENKINS-25258 and https://issues.jenkins-ci.org/browse/JENKINS-24402

Tested this patch. RTBC. Please pull.

**Comment by toshihiko-okubo** [comment]
please pull immediately

**Comment by deeky666** [comment]
:+1:

**Comment by trombik** [comment]
same issue on FreeBSD 10.3, OpenSSH 7.2

**Comment by deeky666** [comment]
Is this plugin still maintained? Looks like the author is not active on GH anymore. Maybe it would be possible to fork and continue the plugin???

**Comment by Mobrockers** [comment]
@deeky666 jenkins plugins do not need to be forked to continue development. Anyone can request access to a plugin repository and will most likely get it. Request access on the jenkins developers mailing list if you are interested in mergin this PR  and releasing a new plugin version.

Mailing list: https://groups.google.com/forum/#!forum/jenkinsci-dev

**Comment by christ66** [comment]
@edmund-wagner ping on this issue pull request?

This potentially fixes a few issues:
https://issues.jenkins-ci.org/browse/JENKINS-25412
https://issues.jenkins-ci.org/browse/JENKINS-24402
https://issues.jenkins-ci.org/browse/JENKINS-25258

**Comment by ljader** [comment]
@christ66 I will merge this PR - it compiles locally, newer JSch is being bundled in .hpi file.

Unfortunately JSch does not publish its source code, only changelog http://www.jcraft.com/jsch/ChangeLog, so there is no easy way to verify declared fixes.
Based on my previous experience with JSch it tends to be backward compatibile, so there "should" be" no problems with this change.

**Comment by trombik** [comment]
@ljader does someone need to create a PR asking new release?

**Comment by ljader** [comment]
@trombik there is still an issue with using SSH Credentials from ssh-credentials plugin - I'm still working on it and as soon as it's ready, I'll issue a new release.

**Comment by johnny-b-goode** [comment]
Pasting my email response (edited for clarity) to another user explaining the reason this change had not already been merged, and why there has not been a recent release of this plugin:

The problem is there is a change (PR https://github.com/jenkinsci/ssh-plugin/pull/9) that was integrated that neither @edmund-wagner or I have had time to test. The testing will need to be somewhat more involved than many of the other changes - which is part of the reason I have not been able to get to it. There are a few changes that have been held up for several months waiting on us to test those changes.

I think we need to revert the stuff for the ssh credentials until we can test it and just do a release.

**Pull request merged**
