### PR TITLE
Updating the SSH plugin's base dependencies and bringing in a newer version of JSCH so that it can log into servers (Bugfix)

### PR DESCRIPTION
**Pull request by monksy**
### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by monksy** [comment]
This relates to the numerous tickets for auth failed over bad crypto being defaulted in the latest jsch plugin.
https://issues.jenkins.io/browse/JENKINS-71751

JSCH Plugin update to pick up: https://github.com/jenkinsci/jsch-plugin/releases/tag/0.2.8-65.v052c39de79b_2

**Comment by monksy** [comment]
This requires an escalation because it includes an update to the parent pom upgrading it's JDK version. Which this rolls up to the Jenkins file. 

https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-controllers/why-jenkinsfile-changes-are-not-reflected-in-pr-build

**Comment by monksy** [comment]
At this point this plugin is abandoned ware. If you can get this working and up to date wtih the right pub key auth.. best of luck. 

This pr has gotten the plugin futher up to date but it didn't fix the root issue.

**Comment by basil** [comment]
Closing in favor of #23

**Pull request closed without merging**
